name: CI - RBE

on:
  pull_request:
  push:
    branches:
      - trunk
  workflow_dispatch:

jobs:
  format:
    name: Format
    uses: ./.github/workflows/bazel.yml
    with:
      name: Check format script run
      cache-key: rbe
      ruby-version: jruby-9.4.2.0
      run: ./scripts/github-actions/check-format.sh
  test:
    name: Test
    uses: ./.github/workflows/bazel.yml
    with:
      # TODO: experiment with turning off caches
      name: All RBE tests
      cache-key: rbe
      ruby-version: jruby-9.4.2.0
      run: ./scripts/github-actions/ci-build.sh
